### ISSUE TITLE
[Errno -5] Name has no usable address

### ISSUE THREAD

**Issue by Vt-Vrajendra** [kurokobo/virtualbmc-for-vsphere#21]
I know there is docker version of vbmc4vsphere. My use case is slightly different.
I have my custom docker instance running where I have installed vbmc4vsphere=0.3.0.

I also pre-create the vbmc config file wrt a VM (For some reason, I cannot use vsbmc add cmd)
When I run vsbmcd, I see an error as below:

> 0203833ef9ed:/app# mkdir -p  ~/.vsbmc/Test-01/
> 
> 0203833ef9ed:/app# vi ~/.vsbmc/Test-01/config
> 
> 0203833ef9ed:/app# vsbmcd --foreground
> 
> 2024-06-05 04:17:17,666.666 66 INFO VirtualBMC [-] Started vBMC instance for vm Test-01
> 
> 2024-06-05 04:17:17,668.668 66 INFO VirtualBMC [-] Started vBMC server on port 50891
> 
> 2024-06-05 04:17:17,672.672 67 ERROR VirtualBMC [-] Shutdown vBMC for vm Test-01, cause [Errno -5] Name has no usable address
> 
> Traceback (most recent call last):
> 
>   File "/usr/local/lib/python3.11/site-packages/vbmc4vsphere/manager.py", line 151, in vbmc_runner
> 
>     vbmc.listen(timeout=CONF["ipmi"]["session_timeout"])
> 
>   File "/usr/local/lib/python3.11/site-packages/pyghmi/ipmi/bmc.py", line 192, in listen
> 
>     ipmisession.Session.wait_for_rsp(timeout)
> 
>   File "/usr/local/lib/python3.11/site-packages/pyghmi/ipmi/private/session.py", line 1184, in wait_for_rsp
> 
>     if _poller(timeout=timeout):
> 
>        ^^^^^^^^^^^^^^^^^^^^^^^^
> 
>   File "/usr/local/lib/python3.11/site-packages/pyghmi/ipmi/private/session.py", line 249, in _poller
> 
>     _io_wait(timeout)
> 
>   File "/usr/local/lib/python3.11/site-packages/pyghmi/ipmi/private/session.py", line 179, in _io_wait
> 
>     intsock.sendto(b'\x01', (myself, iosockets[0].getsockname()[1]))
> 
> socket.gaierror: [Errno -5] Name has no usable address

I also verified that same steps works outside the docker

**Comment by kurokobo** [comment]
@Vt-Vrajendra 
Hi, sorry for the late reply, I haven't been feeling well and couldn't find the time to respond.
I don't have an immediate answer, but I think it might be an environment-dependent issue.

If you delete the container and start over, or perform the same task on a different container host, does the issue still occur?
Are the contents of your configuration file correct? Could you provide the contents of your configuration file with any sensitive information masked?

**Comment by Vt-Vrajendra** [comment]
@kurokobo Thank you for the reply.

My config looks something like this

> [VirtualBMC]
username = user
password = ***
address = 127.0.0.1
port = 6231
vm_name = Test-01
viserver = 10.X.X.X
viserver_username = ***@vsphere.local
viserver_password = ****
active = True

**Comment by kurokobo** [comment]
@Vt-Vrajendra 
Ah okay, could you please try using the image any other from Alpine Linux?
The error `socket.gaierror: [Errno -5] Name has no usable address` is from `musl` (the C library for Alpine Linux, instead of commonly used `glibc`).

**Comment by kurokobo** [comment]
Closing due to inactivity.
