### ISSUE TITLE
vbmc start to fail if vcenter have more than 100 virtual machines

### ISSUE THREAD

**Issue by olemmela** [kurokobo/virtualbmc-for-vsphere#5]
Error message in the logs is:

```
2021-09-15 10:51:05,497.497 27 DEBUG VirtualBMC [-] Get power state called for vm compute1v
2021-09-15 10:51:05,654.654 27 ERROR VirtualBMC [-] Error getting the power state of vm compute1v. Error: No VN with matching name compute1v was found
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/vbmc4vsphere/utils.py", line 99, in get_viserver_vm
    raise Exception
Exception

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/vbmc4vsphere/vbmc.py", line 247, in get_power_state
    vm = utils.get_viserver_vm(conn, self.vm_name)
  File "/usr/local/lib/python3.9/site-packages/vbmc4vsphere/utils.py", line 104, in get_viserver_vm
    raise exception.VMNotFound(vm=vm)
vbmc4vsphere.exception.VMNotFound: No VN with matching name compute1v was found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/vbmc4vsphere/vbmc.py", line 466, in handle_raw_request
    return self.get_chassis_status(session)
  File "/usr/local/lib/python3.9/site-packages/pyghmi/ipmi/bmc.py", line 91, in get_chassis_status
    powerstate = self.get_power_state()
  File "/usr/local/lib/python3.9/site-packages/vbmc4vsphere/vbmc.py", line 256, in get_power_state
    raise exception.VirtualBMCError(message=msg)
vbmc4vsphere.exception.VirtualBMCError: Error getting the power state of vm compute1v. Error: No VN with matching name compute1v was found
```

Issue is in RetrievePropertiesEx function which returns max 100 items in one call.
https://github.com/kurokobo/virtualbmc-for-vsphere/blob/master/vbmc4vsphere/utils.py#L94

**Comment by kurokobo** [comment]
@olemmela 
Thanks for contributing! I've released `0.0.8` including your fix 🚀
